table brand_main_Top
	isHidden
	lineageTag: 10f7de94-d998-4d11-841a-b8832d92ecca

	column Id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 68cdbd59-01de-45ae-a825-a582c70a0055
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column brand_main_top
		dataType: string
		isHidden
		lineageTag: 52997cfa-b7ec-463b-b38c-ac4c0b6731a6
		summarizeBy: none
		sourceColumn: brand_main_top
		sortByColumn: Id

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition brand_main_Top = m
		mode: import
		queryGroup: 02_02_Top_tables
		source = ```
				let
				    Источник = Sql.Database(mssql_server, db_name, 
				    [Query="select distinct brand_main as brand_main_top from all_reports_ad_dict_view where cleaning_flag in (" & cleaning_flag & ")"]),
				    other_table = Table.FromRecords({
				        [brand_main_top="ОСТАЛЬНОЕ"]
				    }),
				    combine_tbl = Table.Combine({other_table, Источник}),
				    #"Добавлен индекс" = Table.AddIndexColumn(combine_tbl, "Id", 1, 1, Int64.Type),
				    #"Строки с примененным фильтром" = Table.SelectRows(#"Добавлен индекс", each [brand_main_top] <> null and [brand_main_top] <> "")
				in
				    #"Строки с примененным фильтром"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Навигация

