table campaigns_dict
	isHidden
	lineageTag: e88f5043-3be4-4c70-b2cb-00ad78c260be

	column start_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: ca660e37-004f-4b5f-bfbc-f853584d5cd5
		summarizeBy: none
		sourceColumn: start_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column campaign_category
		dataType: string
		isHidden
		lineageTag: 5dbcaa7a-f63e-4103-8623-76eb9e627a41
		summarizeBy: none
		sourceColumn: campaign_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		isHidden
		lineageTag: 2b621900-5154-48d3-8185-b95935b21b20
		summarizeBy: none
		sourceColumn: campaign_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		isHidden
		lineageTag: c0a29e83-eb29-42ed-a97b-6b8c1e5fdf6f
		summarizeBy: none
		sourceColumn: status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition campaigns_dict = m
		mode: import
		queryGroup: 03_Общие_справочники
		source =
				let
				    Источник = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRLcLAM3N250g4mGfNOShfQsuWk-xk_8zvR_fj-3LlZx-38DC7yAZv-QTMb87RVnn-exGGHRhvYk2hW/pub?gid=2016378575&single=true&output=csv"),
				    [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Повышенные заголовки" = Table.PromoteHeaders(Источник, [PromoteAllScalars=true]),
				    #"Текст в верхнем регистре" = Table.TransformColumns(#"Повышенные заголовки",{{"status", Text.Upper, type text}, {"campaign_category", Text.Upper, type text}}),
				    #"Измененный тип" = Table.TransformColumnTypes(#"Текст в верхнем регистре",{{"start_date", type date}}),
				    #"Удаленные ошибки" = Table.RemoveRowsWithErrors(#"Измененный тип", {"start_date"})
				in
				    #"Удаленные ошибки"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

