table locations_dict
	lineageTag: 89774b91-5fac-41f4-820b-60a6de07640c

	column locationName
		dataType: string
		lineageTag: 2bcec000-3c17-4b03-a4cf-df63fc20a6eb
		summarizeBy: none
		sourceColumn: locationName
		sortByColumn: locationId

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column locationId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 93c9f61a-1fad-45b3-b276-e381118298ed
		summarizeBy: none
		sourceColumn: locationId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition locations_dict = m
		mode: import
		queryGroup: 08_Big_tv\08_01_Справочники
		source =
				let
				    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WujDlwr4Le3QUgPSGi+0XNijpKBkqxeoAJSZd2Hthq8KFLSB5oKiJUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [locationName = _t, locationId = _t]),
				    #"Измененный тип" = Table.TransformColumnTypes(Источник,{{"locationId", Int64.Type}})
				in
				    #"Измененный тип"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

