table выборТОП
	isHidden
	lineageTag: c26bf3b7-a1aa-4b4c-965b-301df5b376d7

	column Top
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bcd53ff1-ed08-4af0-b0d9-559f1088d6f1
		summarizeBy: sum
		sourceColumn: Top

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Top_txt
		dataType: string
		isHidden
		lineageTag: e4a151b2-95aa-45dc-a9b0-5457029befe3
		summarizeBy: none
		sourceColumn: Top_txt
		sortByColumn: Top

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition выборТОП = m
		mode: import
		queryGroup: 02_01_Вспомогательные_таблицы
		source = ```
				let
				    Источник = Table.FromList(
				{1..10, 12, 15, 20}, 
				Splitter.SplitByNothing(),
				type table[Top = Int64.Type]),
				    #"Дублированный столбец" = Table.DuplicateColumn(Источник, "Top", "Top_txt"),
				    #"Измененный тип" = Table.TransformColumnTypes(#"Дублированный столбец",{{"Top_txt", type text}})
				in
				    #"Измененный тип"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Навигация

